
os: linux

language: cpp

compiler:
    - clang
    - gcc

env:
    - TEST_DIR=libraries/graaf
    - TEST_DIR=libraries/woordstroom
    - TEST_DIR=libraries/csv

before_script:
    - cd $TEST_DIR
    - sh generate_makefile.sh
    - cd build

script: make
