
os: linux

addons:
    apt:
        sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
        packages:
            - cmake-data
            - cmake
            - g++-7
            - clang-5.0

language: cpp

compiler:
    - clang
    - gcc

env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - TEST_DIR = libraries/graaf
    - TEST_DIR = libraries/woordstroom

before_install:
    - eval "${MATRIX_EVAL}"

before_script:
    - cd $TEST_DIR
    - sh generate_makefile.sh
    - cd build

script: make
