
os: linux

language: cpp

compiler:
    - gcc

env:
    - TEST_DIR=libraries
    - TEST_DIR=2016-2017/labo-03-dynamisch-programmeren
    - TEST_DIR=2017-2018/labo-5-stroomnetwerken
    - TEST_DIR=2017-2018/labo-6-samenhangende-componenten
    - TEST_DIR=2017-2018/labo-8-automaten

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-8

before_script:
    - cd $TEST_DIR
    - sh generate_makefile.sh
    - cd build

# TODO: support voor unittests toevoegen
script: make && ./unittest*
