
os: linux

language: cpp

compiler:
    - clang
    # - gcc

env:
    - TEST_DIR=libraries
    # - TEST_DIR=2017-2018/labo-5-stroomnetwerken # travis kent nog geen c++14
    - TEST_DIR=2017-2018/labo-6-samenhangende-componenten
    - TEST_DIR=2017-2018/labo-8-automaten

before_script:
    - cd $TEST_DIR
    - sh generate_makefile.sh
    - cd build

# TODO: support voor unittests toevoegen
script: make
