
os: linux

language: cpp

compiler:
    - clang
    # - gcc

env:
    - TEST_DIR=libraries/graaf
    - TEST_DIR=libraries/woordstroom
    - TEST_DIR=libraries/csv
    - TEST_DIR=2017-2018/labo-5-stroomnetwerken
    - TEST_DIR=2017-2018/labo-8-automaten

before_script:
    - cd $TEST_DIR
    - sh generate_makefile.sh
    - cd build

script: make
